In [1]:
import numpy as np
np.random.rand(25)

array([0.61874427, 0.51997734, 0.19061782, 0.44441907, 0.71360025,
       0.16790434, 0.40312447, 0.49653036, 0.11902318, 0.90521265,
       0.76699592, 0.49650564, 0.58626626, 0.23592405, 0.23077713,
       0.47584961, 0.24052251, 0.79292861, 0.69802107, 0.85399647,
       0.54593604, 0.21758165, 0.91287931, 0.74310166, 0.86600722])

In [2]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [3]:
import numpy as np
array = np.arange(100).reshape(10,10)
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [4]:
print(array[[1,5,6]])

[[10 11 12 13 14 15 16 17 18 19]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]


In [5]:
print(array[3:])

[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [6]:
print(array[0:10,3:8])

[[ 3  4  5  6  7]
 [13 14 15 16 17]
 [23 24 25 26 27]
 [33 34 35 36 37]
 [43 44 45 46 47]
 [53 54 55 56 57]
 [63 64 65 66 67]
 [73 74 75 76 77]
 [83 84 85 86 87]
 [93 94 95 96 97]]


In [7]:
print(array[2:5,1:8])

[[21 22 23 24 25 26 27]
 [31 32 33 34 35 36 37]
 [41 42 43 44 45 46 47]]


In [8]:
np.random.rand(100)

array([0.77756268, 0.44186657, 0.32320288, 0.68809145, 0.00757348,
       0.1384288 , 0.40911199, 0.03124955, 0.38708191, 0.11253765,
       0.06270202, 0.45401979, 0.07607447, 0.49225213, 0.10909704,
       0.45273583, 0.40551613, 0.85638476, 0.17040795, 0.20998246,
       0.93082764, 0.35998324, 0.87073442, 0.69716827, 0.58988011,
       0.13827683, 0.99448417, 0.24414286, 0.08322074, 0.18035662,
       0.19225006, 0.54253088, 0.52586909, 0.12795982, 0.42609652,
       0.68852278, 0.36844913, 0.69859271, 0.66004471, 0.30807041,
       0.96474388, 0.29682857, 0.49008558, 0.594707  , 0.57024788,
       0.29468321, 0.53356937, 0.7206583 , 0.16120758, 0.98989758,
       0.28240592, 0.6083485 , 0.24643518, 0.30119246, 0.39497639,
       0.46871098, 0.95051344, 0.31355423, 0.59723911, 0.32639236,
       0.83574797, 0.79423861, 0.78725748, 0.50816654, 0.36782729,
       0.17471387, 0.31237543, 0.64700099, 0.18850962, 0.53410945,
       0.64619552, 0.85089914, 0.37635481, 0.34400888, 0.38299

In [9]:
a = np.array([[7, 2], [5, 4]])
np.mean(a)

4.5

In [10]:
np.median(a)

4.5

In [11]:
np.std(a)

1.8027756377319946

In [12]:
a = np.array([[7, 1, 1, 7],
             [9, 4, 3, 8],
             [6, 1, 9, 7],
             [9, 7, 2, 5],
             [5, 1, 5, 9]])
a

array([[7, 1, 1, 7],
       [9, 4, 3, 8],
       [6, 1, 9, 7],
       [9, 7, 2, 5],
       [5, 1, 5, 9]])

In [13]:
from scipy import stats
stats.mode(a)

ModeResult(mode=array([[9, 1, 1, 7]]), count=array([[2, 3, 1, 2]]))